"""add cascade delete to songs

Revision ID: 284059a9d6da
Revises: e636bfadc02b
Create Date: 2026-09-04 22:00:53.943585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '284059a9d6da'
down_revision: Union[str, Sequence[str], None] = 'e636bfadc02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('songs_playlist_id_fkey'), 'songs', type_='foreignkey')
    op.create_foreign_key(None, 'songs', 'playlists', ['playlist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.create_foreign_key(op.f('songs_playlist_id_fkey'), 'songs', 'playlists', ['playlist_id'], ['id'])
    # ### end Alembic commands ###
