"""updated songs table

Revision ID: fba3f6a69f5f
Revises: 9b71d059a85b
Create Date: 2026-08-24 18:30:46.484824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fba3f6a69f5f'
down_revision: Union[str, Sequence[str], None] = '9b71d059a85b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('youtube_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('songs', sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'thumbnail_url')
    op.drop_column('songs', 'youtube_url')
    # ### end Alembic commands ###
