"""add is favourite to songs

Revision ID: fee26b21f658
Revises: 284059a9d6da
Create Date: 2026-09-06 06:09:39.007471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fee26b21f658'
down_revision: Union[str, Sequence[str], None] = '284059a9d6da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'songs',
        sa.Column(
            'is_favorite',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'is_favorite')
    # ### end Alembic commands ###
