"""add mood range constraints

Revision ID: eb5c40efeac7
Revises: f192296734a7
Create Date: 2026-08-27 03:11:58.777604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb5c40efeac7'
down_revision: Union[str, Sequence[str], None] = 'f192296734a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_mood_entries_angry_range', 'mood_entries', 'angry BETWEEN 1 AND 5')
    op.create_check_constraint('ck_mood_entries_anxious_range', 'mood_entries', 'anxious BETWEEN 1 AND 5')
    op.create_check_constraint('ck_mood_entries_calm_range', 'mood_entries', 'calm BETWEEN 1 AND 5')
    op.create_check_constraint('ck_mood_entries_energetic_range', 'mood_entries', 'energetic BETWEEN 1 AND 5')
    op.create_check_constraint('ck_mood_entries_happy_range', 'mood_entries', 'happy BETWEEN 1 AND 5')
    op.create_check_constraint('ck_mood_entries_sad_range', 'mood_entries', 'sad BETWEEN 1 AND 5')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_mood_entries_sad_range', 'mood_entries', type_='check')
    op.drop_constraint('ck_mood_entries_happy_range', 'mood_entries', type_='check')
    op.drop_constraint('ck_mood_entries_energetic_range', 'mood_entries', type_='check')
    op.drop_constraint('ck_mood_entries_calm_range', 'mood_entries', type_='check')
    op.drop_constraint('ck_mood_entries_anxious_range', 'mood_entries', type_='check')
    op.drop_constraint('ck_mood_entries_angry_range', 'mood_entries', type_='check')
    # ### end Alembic commands ###
