"""changed moodentry col name

Revision ID: f192296734a7
Revises: fbc9039ce58e
Create Date: 2026-08-27 00:34:08.123489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f192296734a7'
down_revision: Union[str, Sequence[str], None] = 'fbc9039ce58e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood_entries', sa.Column('happy', sa.Integer(), nullable=False))
    op.add_column('mood_entries', sa.Column('calm', sa.Integer(), nullable=False))
    op.add_column('mood_entries', sa.Column('anxious', sa.Integer(), nullable=False))
    op.add_column('mood_entries', sa.Column('sad', sa.Integer(), nullable=False))
    op.add_column('mood_entries', sa.Column('angry', sa.Integer(), nullable=False))
    op.drop_column('mood_entries', 'sadness')
    op.drop_column('mood_entries', 'happiness')
    op.drop_column('mood_entries', 'anger')
    op.drop_column('mood_entries', 'anxiety')
    op.drop_column('mood_entries', 'calming')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood_entries', sa.Column('calming', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('mood_entries', sa.Column('anxiety', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('mood_entries', sa.Column('anger', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('mood_entries', sa.Column('happiness', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('mood_entries', sa.Column('sadness', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('mood_entries', 'angry')
    op.drop_column('mood_entries', 'sad')
    op.drop_column('mood_entries', 'anxious')
    op.drop_column('mood_entries', 'calm')
    op.drop_column('mood_entries', 'happy')
    # ### end Alembic commands ###
