"""Removed album and genre col

Revision ID: fbc9039ce58e
Revises: fba3f6a69f5f
Create Date: 2026-08-26 02:57:23.403144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fbc9039ce58e'
down_revision: Union[str, Sequence[str], None] = 'fba3f6a69f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'genre')
    op.drop_column('songs', 'album')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('album', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('songs', sa.Column('genre', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
